FROM node:14
ENV NODE_ENV=local

# The parent image node:14 appears to have an existing group and user with gid/uid 1000
RUN groupadd -g 1001 stackassist
RUN useradd -u 1001 -g stackassist -ms /bin/bash rootless

RUN chown rootless:stackassist /tmp

USER rootless
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --local

COPY . .

CMD [ "node", "backend.js" ]
